# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'Ubuntu 16.04'

trigger:
  branches:
    include:
    - master

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g gatsby-cli
  displayName: 'install gatsby'

- script: |
    cd Website
    npm install
    npx gatsby build
  displayName: 'gatsby build'

- script: |
      python -m pip install --upgrade pip==9.0.3 setuptools wheel
      pip install awscli --user
  displayName: 'Install tools'

- task: AWSShellScript@1
  inputs:
    awsCredentials: 'aws_tokens'
    regionName: 'us-east-2'
    scriptType: 'inline'
    inlineScript: |
    eval $(/home/vsts/.local/bin/aws ecr get-login --no-include-email)


- task: CopyFiles@2
  inputs:
    sourceFolder: 'public'
    contents: '**' 
    targetFolder: $(Build.ArtifactStagingDirectory)
    cleanTargetFolder: true 
  displayName: 'copy built site'


- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'drop' 
    publishLocation: 'Container'
